/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Departments: () => import('#controllers/departments_controller'),
  LateEntries: () => import('#controllers/late_entries_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
