/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class DepartmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = DepartmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LateEntrySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'durationMinutes',
    'id',
    'lateDate',
    'userId',
    'weekNumber',
    'year',
  ] as const
  $columns = LateEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare durationMinutes: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lateDate: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare weekNumber: number | null
  @column()
  declare year: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'departmentId',
    'email',
    'fullName',
    'id',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentId: number | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
